-- 문종 쿼리
ALTER TABLE FOOD_CATEGORY
MODIFY CNO VARCHAR2(20);


CREATE OR REPLACE VIEW FLIST
AS
SELECT B.POST_NO, B.POST_TITLE, B.RECO_COUNT, E.LOCAL_NAME, E.ADDRESS, E.STAR, E.AREA_X, E.AREA_Y, M.NICKNAME, I.CHANGE_NAME, FC.CNO
FROM B_COMMON B
JOIN EAT E ON (B.POST_NO = E.POST_NO)
JOIN MEMBER M ON (B.WRITER = M.USER_ID)
JOIN IMAGE I ON (B.POST_NO = I.POST_NO)
JOIN FOOD_CATEGORY FC ON (B.POST_NO = FC.POST_NO)
WHERE I.FILE_LEVEL = 0 AND B.DELETE_YN = 'N';


CREATE OR REPLACE VIEW FDETAIL
AS
SELECT B.POST_NO, B.POST_TITLE, B.RECO_COUNT, B.CONTENT, B.VIEW_COUNT, E.RC_FOOD, E.LOCAL_NAME, E.ADDRESS, E.STAR, E.AREA_X, E.AREA_Y, M.NICKNAME
FROM B_COMMON B
JOIN EAT E ON (B.POST_NO = E.POST_NO)
JOIN MEMBER M ON (B.WRITER = M.USER_ID)
WHERE B.DELETE_YN = 'N';


ALTER TABLE TRIP ADD(BEST_TIME VARCHAR2(50));


CREATE OR REPLACE VIEW TLIST
AS
SELECT B.POST_NO, B.POST_TITLE, B.RECO_COUNT, T.LOCAL_NAME, T.ADDRESS, T.STAR, T.AREA_X, T.AREA_Y, M.NICKNAME, I.CHANGE_NAME
FROM B_COMMON B
JOIN TRIP T ON (B.POST_NO = T.POST_NO)
JOIN MEMBER M ON (B.WRITER = M.USER_ID)
JOIN IMAGE I ON (B.POST_NO = I.POST_NO)
WHERE I.FILE_LEVEL = 0 AND B.DELETE_YN = 'N';


CREATE OR REPLACE VIEW TDETAIL
AS
SELECT B.POST_NO, B.POST_TITLE, B.RECO_COUNT, B.CONTENT, B.VIEW_COUNT, T.CAUTION, T.BEST_TIME, T.LOCAL_NAME, T.ADDRESS, T.STAR, T.AREA_X, T.AREA_Y, M.NICKNAME
FROM B_COMMON B
JOIN TRIP T ON (B.POST_NO = T.POST_NO)
JOIN MEMBER M ON (B.WRITER = M.USER_ID)
WHERE B.DELETE_YN = 'N';


COMMIT;